import { NextResponse } from 'next/server';
import { randomInt } from 'node:crypto';
import { DEMO_USER_ID, pool } from '@/lib/db';
import { calculateNextReview } from '@/lib/spaced-repetition';
import { isRegularItalianVerb } from '@/lib/italian-conjugation';
import { supportsLanguage } from '@/lib/languages';
export const dynamic = 'force-dynamic';
function shuffle<T>(items:T[]){const result=[...items];for(let i=result.length-1;i>0;i-=1){const j=randomInt(i+1);[result[i],result[j]]=[result[j],result[i]]}return result}
function positions(length:number){if(length===1)return[randomInt(3)];const base=Array.from({length},(_,i)=>i%3);for(let attempt=0;attempt<50;attempt+=1){const result=shuffle(base);if(result.every((value,i)=>i===0||value!==result[i-1]))return result}return shuffle(base)}
function options(correct:string,distractors:string[],position:number){const values=[correct,...shuffle(distractors.filter(value=>value!==correct)).slice(0,2)];const current=values.indexOf(correct);if(position<values.length&&current!==position)[values[current],values[position]]=[values[position],values[current]];return values}
export async function GET(request:Request){try{const language=new URL(request.url).searchParams.get('language')||'it';if(!supportsLanguage(language))return NextResponse.json({error:'Unsupported language.'},{status:400});const [due,allWords]=await Promise.all([pool.query(`SELECT ul.id,l.target_text AS "targetText",s.translation,l.grammatical_type AS type,ul.mastery_level AS "masteryLevel",'word' AS "itemKind",l.is_irregular AS "isIrregular",COALESCE((SELECT json_agg(json_build_object('tense',lc.tense,'person',lc.person,'form',lc.form,'translation',lc.translation)) FROM language_lexeme_conjugations lc WHERE lc.lexeme_id=l.id),'[]'::json) AS "helperForms" FROM user_lexemes ul JOIN language_lexemes l ON l.id=ul.lexeme_id LEFT JOIN language_lexeme_senses s ON s.id=ul.selected_sense_id WHERE ul.user_id=$1 AND l.language_code=$2 AND ul.next_review_at<=NOW()`,[DEMO_USER_ID,language]),pool.query(`SELECT s.translation FROM user_lexemes ul JOIN language_lexeme_senses s ON s.id=ul.selected_sense_id JOIN language_lexemes l ON l.id=ul.lexeme_id WHERE ul.user_id=$1 AND l.language_code=$2`,[DEMO_USER_ID,language])]);const distractors=allWords.rows.map(row=>row.translation);const shuffledWords=shuffle(due.rows);const answerPositions=positions(shuffledWords.length);const words=shuffledWords.map((word,index)=>({ ...word,helperForms:language==='it'&&!word.isIrregular&&isRegularItalianVerb(word.targetText)?[]:word.helperForms,options:options(word.translation,distractors,answerPositions[index])}));return NextResponse.json({words},{headers:{'Cache-Control':'no-store, max-age=0'}})}catch(error){console.error(error);return NextResponse.json({error:'Could not load reviews.'},{status:500})}}
export async function POST(request:Request){try{const {wordId,itemKind,isCorrect}=await request.json();if(typeof wordId!=='string'||!['word','conjugation'].includes(itemKind)||typeof isCorrect!=='boolean')return NextResponse.json({error:'Invalid review response.'},{status:400});if(itemKind!=='word')return NextResponse.json({error:'Conjugation review uses the forms review endpoint.'},{status:400});const current=await pool.query('SELECT mastery_level AS "masteryLevel" FROM user_lexemes WHERE id=$1 AND user_id=$2',[wordId,DEMO_USER_ID]);if(!current.rows[0])return NextResponse.json({error:'Review item not found.'},{status:404});const next=calculateNextReview(isCorrect,Number(current.rows[0].masteryLevel));await pool.query('UPDATE user_lexemes SET mastery_level=$1,next_review_at=$2,last_reviewed_at=NOW() WHERE id=$3 AND user_id=$4',[next.masteryLevel,next.nextReviewAt,wordId,DEMO_USER_ID]);return NextResponse.json(next)}catch(error){console.error(error);return NextResponse.json({error:'Could not update review.'},{status:500})}}
